/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BbvPlanningPoker {
    }
    interface PageCardDetail {
        "deckId": string;
    }
    interface PageCardOverview {
    }
    interface PageSettings {
    }
    interface PokerCard {
        "color": string;
    }
    interface PokerCardDeck {
    }
}
declare global {
    interface HTMLBbvPlanningPokerElement extends Components.BbvPlanningPoker, HTMLStencilElement {
    }
    var HTMLBbvPlanningPokerElement: {
        prototype: HTMLBbvPlanningPokerElement;
        new (): HTMLBbvPlanningPokerElement;
    };
    interface HTMLPageCardDetailElement extends Components.PageCardDetail, HTMLStencilElement {
    }
    var HTMLPageCardDetailElement: {
        prototype: HTMLPageCardDetailElement;
        new (): HTMLPageCardDetailElement;
    };
    interface HTMLPageCardOverviewElement extends Components.PageCardOverview, HTMLStencilElement {
    }
    var HTMLPageCardOverviewElement: {
        prototype: HTMLPageCardOverviewElement;
        new (): HTMLPageCardOverviewElement;
    };
    interface HTMLPageSettingsElement extends Components.PageSettings, HTMLStencilElement {
    }
    var HTMLPageSettingsElement: {
        prototype: HTMLPageSettingsElement;
        new (): HTMLPageSettingsElement;
    };
    interface HTMLPokerCardElement extends Components.PokerCard, HTMLStencilElement {
    }
    var HTMLPokerCardElement: {
        prototype: HTMLPokerCardElement;
        new (): HTMLPokerCardElement;
    };
    interface HTMLPokerCardDeckElement extends Components.PokerCardDeck, HTMLStencilElement {
    }
    var HTMLPokerCardDeckElement: {
        prototype: HTMLPokerCardDeckElement;
        new (): HTMLPokerCardDeckElement;
    };
    interface HTMLElementTagNameMap {
        "bbv-planning-poker": HTMLBbvPlanningPokerElement;
        "page-card-detail": HTMLPageCardDetailElement;
        "page-card-overview": HTMLPageCardOverviewElement;
        "page-settings": HTMLPageSettingsElement;
        "poker-card": HTMLPokerCardElement;
        "poker-card-deck": HTMLPokerCardDeckElement;
    }
}
declare namespace LocalJSX {
    interface BbvPlanningPoker {
    }
    interface PageCardDetail {
        "deckId"?: string;
    }
    interface PageCardOverview {
    }
    interface PageSettings {
    }
    interface PokerCard {
        "color"?: string;
    }
    interface PokerCardDeck {
    }
    interface IntrinsicElements {
        "bbv-planning-poker": BbvPlanningPoker;
        "page-card-detail": PageCardDetail;
        "page-card-overview": PageCardOverview;
        "page-settings": PageSettings;
        "poker-card": PokerCard;
        "poker-card-deck": PokerCardDeck;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bbv-planning-poker": LocalJSX.BbvPlanningPoker & JSXBase.HTMLAttributes<HTMLBbvPlanningPokerElement>;
            "page-card-detail": LocalJSX.PageCardDetail & JSXBase.HTMLAttributes<HTMLPageCardDetailElement>;
            "page-card-overview": LocalJSX.PageCardOverview & JSXBase.HTMLAttributes<HTMLPageCardOverviewElement>;
            "page-settings": LocalJSX.PageSettings & JSXBase.HTMLAttributes<HTMLPageSettingsElement>;
            "poker-card": LocalJSX.PokerCard & JSXBase.HTMLAttributes<HTMLPokerCardElement>;
            "poker-card-deck": LocalJSX.PokerCardDeck & JSXBase.HTMLAttributes<HTMLPokerCardDeckElement>;
        }
    }
}
